- playground/playground.js
Hi team 👋 
`parcel-css` is a great library! I wanted to help something, and I watched this project.
As the [`prettier` playground](https://prettier.io/playground/) and [`swc` playground](https://swc.rs/playground) does, 
How about saving the input state of `parcel-css`'s playground as a URLHash and restoring it on load? This will make it easier to report and reproduce issues.
https://user-images.githubusercontent.com/42742053/145522152-f2d25c0c-87e9-4eca-9592-20ac43712370.mov
This is just a proposal, so if you don’t think it is necessary, please be free to close this PR.
> Feature proposal: save and load playground state as URLHash

- build-prefixes.js
- node/index.d.ts
- node/src/lib.rs
- playground/index.html
- playground/playground.js
- selectors/builder.rs
- selectors/matching.rs
- selectors/parser.rs
- src/compat.rs
- src/lib.rs
- src/parser.rs
- src/rules/document.rs
- src/rules/media.rs
- src/rules/mod.rs
- src/rules/nesting.rs
- src/rules/style.rs
- src/rules/supports.rs
- src/selector.rs
- src/stylesheet.rs
- test.js
> Implement CSS Nesting

- node/index.d.ts
- node/src/lib.rs
- src/dependencies.rs
- src/lib.rs
- src/printer.rs
- src/properties/transform.rs
- src/properties/ui.rs
- src/rules/font_face.rs
- src/rules/mod.rs
- src/stylesheet.rs
- src/traits.rs
- src/values/image.rs
- src/values/mod.rs
- src/values/url.rs
- test.js
#18
Collects `@import` and `url()` dependencies and returns descriptors for them when the `analyzeDependencies` option is true. Also removes `@import` rules completely and replaces urls with placeholders during printing. This is needed for bundling, but may be too Parcel-specific... Should it be a separate option? 🤔
> Dependency analysis

- README.md
Hi ! 👋 
I noticed the link into TypeScript definitions in ["From JavaScript"](https://github.com/parcel-bundler/parcel-css#from-javascript) section is wrong. The relative path in `README.md` is resolved with branch prefix automatically, so `blob/master/path` is resolved to `https://github.com/org/repo/blob/master/blob/master/path`.
FYI: https://github.blog/2013-01-31-relative-links-in-markup-files/
I fixed this. In the first place, the rule of relative path of GitHub is difficult to understand, so I decided to specify it with an absolute path.
> Chore: fix wrong url into TypeScript definition file in README

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- README.md
- package.json
- scripts/build-npm.js
- scripts/build-wasm.js
This adds a `@parcel/css-wasm` package which can be used in Deno or directly in browsers.
> Publish WASM package

- Cargo.lock
- Cargo.toml
- src/main.rs
This PR ships with a basic implementation of a CLI for parcel-css using clap-rs.
Resolves #36
> Add basic CLI

- src/stylesheet.rs
This PR allows Rust users to construct a new `StyleSheet` instance with a static `new` method.
Resolves #46
> feat: added static method StyleSheet::new

- scripts/build-prefixes.js
- src/prefixes.rs
In some of the compatibility tables, I found that min and max are the same.
So, I added a part to change from Ord to Eq.
> Simplify comparison compat

- Cargo.lock
- Cargo.toml
- README.md
- node/index.d.ts
- node/src/lib.rs
- playground/index.html
- playground/playground.js
- scripts/build-prefixes.js
- src/compat.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/media_query.rs
- src/parser.rs
- src/rules/custom_media.rs
- src/rules/document.rs
- src/rules/media.rs
- src/rules/mod.rs
- src/rules/nesting.rs
- src/rules/style.rs
- src/rules/supports.rs
- src/stylesheet.rs
Fixes #49.
This adds basic support for the `@custom-media` rule, and referencing custom media queries in `@media` rules. It will error on complex boolean logic with media types (e.g. screen, print, etc.) because that is too hard to compile and seems unlikely to be used. See https://github.com/parcel-bundler/parcel-css/issues/49#issuecomment-1013897432. It will also error on circular media queries, and undefined references.
To do
> Add support for custom media queries

- Cargo.lock
- Cargo.toml
- src/main.rs
- tests/cli_integration_tests.rs
Address parts of #52, but not `--targets` or transforming multiple files.
* makes `--minify` a boolean option, instead of a subcommand
* instead of  `--input-file` option as part of the minify subcommand, input file is now a required positional arg
* moves `--output-file` from subcommand to the top level
* adds `--nesting` boolean option, to enable nesting
* adds `--css-modules` and `--css-modules-output-file` options
* adds `--sourcemap` option
* adds integration tests in rust for the CLI in `tests/cli_integration_tests.rs`
CSS Modules and sourcemap options make what seem to me like decent default choices for where to send their output. 
* Sourcemap requires an output file, since it doesn't make sense to have a sourcemap without a file...
* if there's an output file `out.css`, then the …
> Add sourcemap, nesting, and css-modules CLI flags

- Cargo.toml
I think it would be beneficial for library use cases to make the binary-only dependencies (i.e. `clap`) optional. This PR adds a (default) "cli" feature to that end.
Thanks for the excellent project!
> Add "cli" Cargo feature to make binary-only dependencies optional.

- src/lib.rs
- src/rules/mod.rs
Hi there! 👋🏽 
I was exploring `@parcel/css` and noticed `!important` declarations were excluded from the output - [playground link](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%7D%5Cn.foo%20%7B%5Cn%20%20background%3A%20green%20!important%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D).
I don't know if it's by default so I took some time to dig into the source code and change this behaviour. If it's by default, please close this PR.
If it's not, let me know if I missed something or you have any suggestions.
PS: I was wondering if we need a similar check as this …
> Merge important declarations of adjacent rules

- src/lib.rs
- src/properties/font.rs
CSS wide keywords are confusingly defined(see https://github.com/w3c/csswg-drafts/issues/7170), we left out `revert` and `revert-layer`, and we can't remove the quotes when these keywords are present.
Improvement #120
> fix: `font-family: revert/revert-layer` cannot remove quotation marks

- .github/workflows/test.yml
- rust-toolchain.toml
- src/media_query.rs
This commit updates CI to also run on PRs. Additionally CI now fails if
build warnings are encountered.
A `rust-toolchain.toml` file has been added to the root of the repo that
ensures that all collaboraters use the same up-to-date Rust version.
Cargo picks up this file automatically and uses rustup to install and
use the right version of rustc and cargo for each project.
CI now also adheres to this toolchain file through the use of
`dtolnay/rust-toolchain@stable`.
> CI on PRs, fix build warning, fixed rust version

- src/lib.rs
- src/properties/border.rs
If just color, or color and style for a border were ommited, an
extraneous space char would be present at the end of the property value
output. This commit fixes this by inserting spaces before values rather
than after.
Fixes #130
> Fix extraneous trailing space for border property

- src/dependencies.rs
- src/lib.rs
- src/media_query.rs
- src/printer.rs
- src/properties/mod.rs
- src/properties/transform.rs
- src/rules/mod.rs
- src/selector.rs
- src/stylesheet.rs
- src/traits.rs
- src/values/angle.rs
- src/values/length.rs
- src/values/percentage.rs
Part of #5.
This exposes the `Parse` and `ToCss` traits, which can be used to parse and serialize individual CSS rules, properties, and values rather than only entire stylesheets. I also added `parse_string` and `to_css_string` convenience functions to parse and serialize from a string, without manually constructing a parser/printer from scratch.
By extension, this means the `Printer` is also exposed. I've refactored it a little to accept an options struct and also to hide internal fields.
Example:
```rust
use parcel_css::{
properties::Property,
rules::CssRule,
stylesheet::{ParserOptions, PrinterOptions},
traits::{Parse, ToCss},
values::color::CssColor,
};
// Parse and serialize an individual value
let color = CssColor::parse_string("#f0f")?; …
```
> Expose Parse and ToCss traits

- src/lib.rs
- src/properties/mod.rs
- src/values/url.rs
Currently parcel-css removes unnecessary quotation marks from `url("foo")` expressions regardless of whether it is minifying. The Parcel bundler encodes placeholders into these url expressions using the original quotations from user code and removing quotations entirely causes it to produce invalid css when replacing these placeholders (for example, when the url expression contains a data url including a space that has not been url-encoded).
There are a few ways I can think of to solve this:
* Parcel's bundler could detect that the content it is inserting must be re-wrapped in quotations to be valid, or do so unconditionally assuming it will be minified.
* parcel-css can preserve original quotations in its output when not minifying.
* parcel-css can unconditionally include quotations in …
> Always output quoted urls when not minifying

- src/declaration.rs
- src/dependencies.rs
- src/error.rs
- src/lib.rs
- src/rules/style.rs
Closes #168
We don't store source locations for every property/value currently, because that would use a lot of additional memory, and it's rare to need source locations except in errors. So this adds a method to lazily compute the source locations of the keys/values of declarations within a style rule. Essentially, it performs a very lightweight additional parsing pass to first find the stored location of the parent style rule, and then finding the declaration by index from there.
This approach is somewhat error prone (e.g. if you modified the style sheet) so I'm not sure if it's a good idea or not. Alternatives would be to store source locations for everything, which I'd prefer not to do if we can help it, or somehow optionally store them externally (but I'm not sure how).
> Add method to lazily compute property source ranges

- src/bundler.rs
This adds a new `resolve()` method to `SourceProvider` which is responsible for resolving an `@import` specifier into a file path. `FileProvider` still uses the default behavior of assuming the specifier is a relative path and joining it with the path of the originating file. This provides a hook for custom `SourceProviders` to implement their own application-specific resolution logic.
This required a couple minor refactors in the `fs!` and `error_test()` utilities to make them more flexible and support testing a custom resolver.
I've done a little Rust, but I'm not terribly familiar with it, so please let me know if I'm doing anything unidiomatic. Some of the areas I struggled with and am not convinced I found the ideal solution:
1. `error_test()` accepts a callback which runs …
> Add `resolve()` method to `SourceProvider`

- node/src/lib.rs
- src/bundler.rs
- src/css_modules.rs
- src/declaration.rs
- src/dependencies.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/parser.rs
- src/printer.rs
- src/properties/grid.rs
- src/properties/mod.rs
- src/rules/mod.rs
- src/stylesheet.rs
- test.js
Closes #156.
This adds support for custom patterns for generating names in css modules. Using `cssModules: true` continues to use the same default pattern as before, but you can also now set it to a config object:
```js
{
cssModules: {
pattern: 'library-[name]-[hash]-[local]
}
}
```
The currently supported segments are:
* `[name]` - the base name of the file name being transformed, without the extension
* `[hash]` - a hash of the full file path
* `[local]` - the original class name
We could add more if needed as well. The pattern is parsed ahead of time and interpreted when writing out class names. Hopefully this solves the majority of use cases. We could add a JS callback for this as well, but it would add a lot of performance overhead so I would like to avoid it if possible.
> Add support for custom css modules name patterns

- Cargo.toml
- rust-toolchain.toml
- src/media_query.rs
Hi there,
The [retain_mut](https://crates.io/crates/retain_mut) crate has been deprecated and archived now that the functionality has been officially stabilized. That dependency should be removed once you're comfortable bumping this project's MSRV to `1.61.0`.
This pull request does just that. :wink:
> Remove Deprecated `retain_mut` Dependency

- README.md
- scripts/build-prefixes.js
- src/compat.rs
- src/lib.rs
- src/properties/font.rs
The `system-ui` font family is a special font family that will be changed to the platform's default font family.
This feature will add fallback font families when unsupported
```css
.foo {
font-family: Helvetica, system-ui, sans-serif;
}
.bar {
font: 100%/1.5 Helvetica, system-ui, sans-serif;
}
```
becomes
```css
.foo {
font-family: Helvetica, system-ui, AppleSystem, BlinkMacSystemFont, Segoe UI, Roboto, Noto Sans, Ubuntu, Cantarell, Helvetica Neue, sans-serif;
}
.bar {
font: 100% / 1.5 Helvetica, system-ui, AppleSystem, BlinkMacSystemFont, Segoe UI, Roboto, Noto Sans, Ubuntu, Cantarell, Helvetica Neue, sans-serif;
}
```
The list of fonts comes from this postcss plugin: https://www.npmjs.com/package/postcss-font-family-system-ui
These are my very first lines of Rust, I'm open to feedback …
> Add support for system-ui fallbacks

- playground/playground.js
- Show errors in the playground (changing the text color to red)
- Stores the current playground state in the URL even if the transform failed
- (Run `loadPlaygroundState` after `await loadVersions()` because the former is synchronous)
> Show errors in playground

- scripts/build-npm.js
the add new `libc` filed help package managers detect which package is relevant better as this is available in newer versions of pnpm, yarn, and cnpm
ref: https://github.com/pnpm/pnpm/issues/4454
> feat: add libc filed

- src/main.rs
My very first rust experience, so be gentle ;)
I wanted a way to get both the resulting code and the CSS modules from the CLI without having to specify an output file, which means I would have to read files to get what I want.
So in this PR, if `output-file` flag is not given, and `css-modules` flag is given, the CLI will return a JSON string containing the code and the CSS modules...
```json
{
"code": ".cLD2Uq_header {\n  background-color: #00f;\n}\n",
"modules": {
"header": { "composes": [], "isReferenced": false, "name": "cLD2Uq_header" }
}
}
```
All other functionality is maintained.
Would appreciate any feedback. thx
> CLI: Return code and CSS modules as JSON when output file is not given

- src/main.rs
This PR adds the new CSS modules options to the CLI.
```
--css-modules-dashed-idents
--css-modules-pattern [<CSS_MODULES_PATTERN>]
```
> CLI: --css-modules-pattern and --css-modules-dashed-idents options

- scripts/build-npm.js
fixes #203
> To avoid this, Yarn now supports a libc array field in the package.json that currently accepts any of two values: glibc and musl. Just like os and cpu, packages will be skipped if they don't match the host libc.
> -- https://dev.to/arcanis/yarn-32-libc-yarn-explain-next-major--o22
Yarn, cnpm, and pnpm will filter optionalDependencies with abi as well, which only understands gcc abi with the name `glibc`, yet `-gnu` is a well conceived abi naming in napi packages. Hence manually set `libc` field to `[ "glibc" ]`.
> set `libc` field to glibc in package.json targeting gnu

- scripts/build-npm.js
Closes #207
Currently Yarn >=2 doesn't install the Windows specific optional package at all.
See https://github.com/parcel-bundler/parcel-css/issues/207#issuecomment-1157479514
> Remove `pkg.libc` property for Windows

- src/lib.rs
- src/rules/layer.rs
- src/rules/mod.rs
Fixes #211
Literally installed Rust a few hours ago, "please go read a Rust tutorial first" is a valid reply and I'd be happy to do another round :)
I'll probably need to do that to implement my other suggestion about hoisting layers. Adjacent style rules are also not merged inside layers, but that's not a regression. I guess it needs another pass of `minify`?
> Merge adjacent layers with the same name

- scripts/build-npm.js
Add the libc field in a clearer and more explicit way.
After this PR, `linux-gnueabihf` also no longer adds the `libc` field.
```json
{
"name": "@parcel/css-linux-arm-gnueabihf",
"libc": [
"gnueabihf"
]
}
```
Related PRs: https://github.com/parcel-bundler/parcel-css/pull/205, https://github.com/parcel-bundler/parcel-css/pull/208
> fix: add libc fields only to platforms that have libc

- Cargo.lock
- Cargo.toml
- c/Cargo.toml
- c/build.rs
- c/cbindgen.toml
- c/parcel_css.h
- c/src/lib.rs
- c/test.c
- src/main.rs
- src/targets.rs
This adds C bindings for Parcel CSS, so that it can be used from programming languages other than Rust. So far, the basics of parsing, transforming, and printing stylesheets are supported. Eventually we might be able to expose information about rules and such as well if needed.
cc. @Jarred-Sumner
> C bindings

- src/lib.rs
- src/rules/font_face.rs
Closes: #254 
https://github.com/parcel-bundler/parcel-css/blob/5a6801ce26f9ae9d07d44d3427de4a6b48663261/src/lib.rs#L9425-L9430
should we have this test, if we should, please tell me how to make it pass correctly, thanks
I tried to propagate the error up
https://github.com/parcel-bundler/parcel-css/blob/5a6801ce26f9ae9d07d44d3427de4a6b48663261/src/rules/font_face.rs#L70-L85
But here the error have been ignored again
https://github.com/parcel-bundler/parcel-css/blob/5a6801ce26f9ae9d07d44d3427de4a6b48663261/src/rules/font_face.rs#L430-L435
> refactor(rules/font_face): change supports to tech

- playground/playground.js
> Playground: Fix wrong text color in output panel

- src/rules/custom_media.rs
- tests/cli_integration_tests.rs
fix #258
Adds a semicolon at the end of the `@custom-media` declaration.
@devongovett thank you for pointing me to the right file!
> fix: Missing semicolon in Custom Media Queries

- src/lib.rs
- src/values/image.rs
Before this PR, we would always remove it when resolution = `1x/1dppx`. This is not compliant with the specification and will not render in the Safari <= 16 .
Input:
```css
body {
background-image: image-set("../images/bg.webp" 1x, "../images/bg.webp" 2x);
}
```
```css
body {
background-image: image-set("../images/bg.webp", "../images/bg.webp" 2x);
}
```
```css
body {
background-image: image-set("../images/bg.webp" 1x, "../images/bg.webp" 2x);
}
```
In the future we need to add detection of `resolution <= 0`.
For example: `image-set(url(example.png) 0x)` is an invalid syntax.
Closes: https://github.com/parcel-bundler/parcel-css/issues/262
> fix: resolution = 1 cannot be omitted from `image-set()`

- Cargo.lock
- README.md
- node/Cargo.toml
- node/index.d.ts
- node/index.mjs
- node/src/lib.rs
- node/src/threadsafe_function.rs
- src/bundler.rs
- test-bundle.mjs
- tests/testdata/baz.css
- tests/testdata/foo.css
- tests/testdata/hello/world.css
This is an alternative approach to #196. This approach doesn't require converting the whole bundler to async. Instead, it uses napi threadsafe functions in combination with channels to wait for the result from the JavaScript thread in the rayon thread.
This required a fork of threadsafe_function.rs from napi-rs to support getting the result of the JS function, which I hope to potentially contribute upstream. This also means there is no required JS wrapper to convert from a callback-based API to a promise-based one.
Still need to do some performance testing to see generally how much a JS resolver slows things down.
cc. @dgp1130
> Support async bundling with JS resolver

- scripts/build-wasm.js
I noticed while using the wasm module within Deno, the `init` function wasn't properly typed. This PR fixes that.
> fix: added types for wasm init default export

- src/lib.rs
- src/rules/font_face.rs
Previously `tech()` was implemented in https://github.com/parcel-bundler/parcel-css/pull/255, and this PR modifies `feature-*` to be plural to match the specification.
Spec changed in: https://github.com/w3c/csswg-drafts/issues/7663#issuecomment-1231534440
Chrome CL: https://chromium-review.googlesource.com/c/chromium/src/+/3856267
Fixes: #254
---
cc @CGQAQ
> fix: match the spec so that feature-* in `tech()` becomes plural

- README.md
With https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/192 the link changed. Also updated the link text to be more accessible than "here"
> Change link to `css-minimzer-webpack-plugin`

- src/lib.rs
- src/properties/animation.rs
In the `animation` property, special handling is required when the values of both `animation-name` and `animation-fill-mode` are `none`.
```css
.foo {
animation: "none";
}
.bar {
animation: "none" 2s;
}
```
```css
.foo {
animation: "none" none;
}
.bar {
animation: "none" 2s none;
}
```
```css
.foo {
animation-name: "none";
}
.bar {
animation: "none" 2s;
}
```
> fix: avoid parsing `animation: "none"` to `animation: "none" none`.

- src/lib.rs
- src/values/color.rs
Currently only enabled when `minify: true`.
```js
let opts = {
minify: true,
targets: {
chrome: 61 << 16,
}
}
```
```css
.foo {
background-color: transparent;
color: rgba(0, 0, 0, 0);
border-color: rgb(0 0 0 / 0%);
background: linear-gradient(90deg, rgba(0, 0, 0, 0), transparent);
}
```
```css
.foo{color:rgba(0,0,0,0);background:linear-gradient(90deg,rgba(0,0,0,0),rgba(0,0,0,0));border-color:rgba(0,0,0,0)}
```
This is consistent with [cssnano](https://cssnano.co/playground/).
```css
.foo{color:transparent;background:linear-gradient(90deg,transparent,transparent);border-color:transparent}
```
> fix: if the browser doesn't support `#rrggbbaa` color syntax, it is converted to `transparent`

- src/lib.rs
- src/properties/border.rs
- src/properties/mod.rs
`border-spacing = <length> <length>?`
Spec: https://www.w3.org/TR/CSS22/tables.html#propdef-border-spacing
> feat: support border-spacing

- selectors/builder.rs
- selectors/matching.rs
- selectors/parser.rs
- src/lib.rs
- src/selector.rs
This is part of https://github.com/parcel-bundler/lightningcss/issues/87
> feat: add `:nth-col()` and `:nth-last-col()` selectors

- src/lib.rs
- src/properties/border_radius.rs
Fixes  #307
This pull request:
- Adds https://github.com/parcel-bundler/lightningcss/issues/307 as test case and fixes it.
- Adds another test case (for `<first> <second> <third> / <first> <second>` syntax) from MDN.
- Fixes a previously false-positive test, caused by consistently placing `bottom-left` (or `start-end`) before `bottom-right` (or `end-end`)
- Prevents future similar bugs and reduces confusion by consistently re-sorting bottom right before bottom left (matching CSS syntax) across the border radius module and tests.
A note about white space: 
Some white space was inconsistent, but that was not meant to be subject of this PR. I accidentally committed the removal of spaces from otherwise empty lines, causing diff noise. With this accidental change, the post-merge code is more …
> Fix flipped `border-bottom-right` and `border-bottom-left`

- README.md
- src/main.rs
- src/targets.rs
- tests/cli_integration_tests.rs
> feat(cli): Load browserslist configuration if no `--targets` supplied.

- README.md
Just a small docs fix; repairing a leftover from sentence reformulation.
> fix(docs): Fix wording in browserslist section

- .github/workflows/release.yml
Fixes #335.
Do to an upstream commit (https://github.com/messense/manylinux-cross/commit/76f103138b2c65450b1d181318004203ef760ad5) on the base docker image use to build the ARM linux binaries, Ubuntu was upgraded to 22.01. This raised the GLIBC requirement to 2.35. For now I pinned to an older version of the docker image to downgrade again.
> Pin debian docker image to fix ARM linux GLIBC requirement

- src/lib.rs
- src/media_query.rs
Fixes #320. Closes #332. Closes #333. Closes #334.
This detects when parentheses are needed in media queries and inserts them during printing. This allows us to remove the `InParens` variant from the AST, which simplifies the code and ensures that any transforms that occur produce valid output. It should also remove parens that aren't needed.
> Fix media query parens

- Cargo.toml
- src/lib.rs
This commit adds a "bundler" feature flag to the lightningcss crate.
We put the "dashmap" and "rayon" dependencies behind this new flag.
Users that do not need the bundler can now disable the feature to save
on compile time.
Related: https://github.com/parcel-bundler/lightningcss/issues/357
> Introduce "bundler" feature flag

- Cargo.lock
- derive/Cargo.toml
This disables the default syn features in lightningcss-derive's
Cargo.toml.
It also removes an unused syn feature.
Related: https://github.com/parcel-bundler/lightningcss/issues/357
> Disable syn default features in lightningcss-derive

- Cargo.toml
- src/lib.rs
- src/printer.rs
- src/rules/container.rs
- src/rules/counter_style.rs
- src/rules/custom_media.rs
- src/rules/document.rs
- src/rules/font_face.rs
- src/rules/font_palette_values.rs
- src/rules/import.rs
- src/rules/keyframes.rs
- src/rules/layer.rs
- src/rules/media.rs
- src/rules/namespace.rs
- src/rules/nesting.rs
- src/rules/page.rs
- src/rules/property.rs
- src/rules/style.rs
- src/rules/supports.rs
- src/rules/unknown.rs
- src/rules/viewport.rs
- src/stylesheet.rs
This commit introduces the "sourcemap" feature.
Users that do not need sourcemaps can disable this feature and save
roughly 15% on compile times.
Related to https://github.com/parcel-bundler/lightningcss/issues/357
> Add sourcemap feature

- selectors/Cargo.toml
- selectors/builder.rs
- selectors/lib.rs
Saves around 3.5% on `lightningcss` compile times on my machine.
> Remove derive-move

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/main.rs
- tests/cli_integration_tests.rs
Resolves parcel-bundler/lightningcss#375
src/main.rs: made input_file optional and use stdin and a fake name if it's None
Cargo.toml: added new cli dependency on atty for detecting pipe
rust-toolchain.toml: bumped version of Rust for stable std::io::read_to_string
tests/cli_integration_tests.rs: removed test for no_input_file
> CLI support for piping

- src/lib.rs
- src/rules/layer.rs
Spec: https://w3c.github.io/csswg-drafts/css-cascade-5/#typedef-layer-name
Closes: #382
> fix: `<layer-name>` should be escaped

- wasm/index.mjs
I'm currently using this in a "classic" (not module) worker and `import.meta.url` is not defined which is breaking the call to the `URL` constructor, which I don't even use because I send in the path the WASM module manually. 
This change uses `import.meta.url` and the `URL` constructor only in the fallback case when a user doesn't pass in a custom url.
> WASM: Only use `import.meta.url` in fallback scenario

- derive/src/lib.rs
- examples/custom_at_rule.rs
- node/src/lib.rs
- node/src/transformer.rs
- src/main.rs
- src/parser.rs
- src/properties/custom.rs
- src/rules/mod.rs
- src/selector.rs
- src/stylesheet.rs
- src/values/color.rs
- src/values/string.rs
- src/vendor_prefix.rs
- src/visitor.rs
In [Classmate](https://github.com/georgeclaghorn/classmate), visitors call fallible Ruby methods. I’d like to stop traversal at the first error and propagate it back up to the caller.
I currently approximate that by storing the error on the visitor and wrapping each `Visitor` method’s body in `if self.error.is_none() { ... }`. It would be nicer if I could just return an error from a visitor method and let it bubble up. This PR makes that possible.
The JS bindings’ `JsVisitor` intentionally remains infallible to preserve existing behavior, where it continues traversal after an error, but it could adopt the new behavior if desired.
> Visitor: allow short-circuiting on error

- Cargo.toml
- src/lib.rs
- src/media_query.rs
- src/parser.rs
- src/printer.rs
- src/properties/custom.rs
- src/properties/grid.rs
- src/properties/mod.rs
- src/properties/text.rs
- src/properties/ui.rs
- src/rules/mod.rs
- src/selector.rs
- src/stylesheet.rs
- src/targets.rs
- src/values/color.rs
- src/values/length.rs
- src/values/string.rs
- src/vendor_prefix.rs
The docs for the `visitor` module currently don't appear on [docs.rs](https://docs.rs/lightningcss/1.0.0-alpha.39/lightningcss/). Fix by enabling all optional features when generating docs for docs.rs. Annotate public items that require optional features.
To test locally, run:
```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --open
```
(Apologies if these docs are intentionally not published.)
References: [Stack Overflow](https://stackoverflow.com/a/61417700).
> Publish docs for optional features on docs.rs

- wasm/index.mjs
As discussed in #386, will try to read from filesystem (using `fs`) if used in a node environment, and fallback to `fetch` for browser/deno environments.
> Support node in wasm package

- src/main.rs
- tests/cli_integration_tests.rs
- Resolves https://github.com/parcel-bundler/lightningcss/issues/421
> Support creating missing directories with `--output-file` option

- package.json
Let me start with - **why**.
While developing my package, I am using TypeScript version `v5.0`.
The build compilation were failing because of the following error:
```
src/cli.ts(5,27): error TS7016: Could not find a declaration file for module 'lightningcss'. '/home/xeho91/Nextcloud/Projects/oss/typewind/node_modules/.pnpm/lightningcss@1.19.0/node_modules/
lightningcss/node/index.mjs' implicitly has an 'any' type.
There are types at '/home/xeho91/Nextcloud/Projects/oss/typewind/packages/typewind/node_modules/lightningcss/node/index.d.ts', but this result could not be resolved when respecting package.
json "exports". The 'lightningcss' library may need to update its package.json or typings.
Error: error occured in dts build
at Worker.<anonymous> …
```
> Add support for TypeScript `moduleResolution` - `bundler`

- Cargo.lock
- selectors/Cargo.toml
We're wanting to [use lightningcss](https://github.com/DioxusLabs/taffy/pull/393) as a dependency in [Taffy](https://github.com/DioxusLabs/taffy). However our CI is [complaining](https://github.com/DioxusLabs/taffy/actions/runs/4394482038/jobs/7695555149) that `lightningcss` is depending on multiple versions of the same crate (which we try to avoid for binary size reasons).
I've tracked this down to `parcel_selectors` crate which depends on `phf 0.8`on `cssparser 0.29` which depends on `phf 0.10`.
- Updates the `parcel_selectors` crate to use `phf 0.10` (no code changes needed)
- Bumps the version of the `parcel_selectors` crate to from `0.25.1` to `0.25.2`
- Updates the `repository` field of `Cargo.toml` to point to this repo
- Updates the `documentatation` field of `Cargo.toml` to point …
> Bump `phf` dependency in `parcel_selectors` crate

- website/docs.css
- website/index.html
Now, website title text is invisible in selection cause it's color is transparent.
Override its color in `::selection` to fix this.
Also the title in docs.
> website: Make title visible in selection

- node/index.d.ts
Can be useful for exposing a set of options for integrating into tools like Vite ;)
(Currently doing `type LightningCSSTargets = ReturnType<typeof browserslistToTargets>`)
> Expose `Targets` in types

- examples/custom_at_rule.rs
This PR resolves https://github.com/parcel-bundler/lightningcss/issues/475 by adding a `nesting` option to an example and fixing a panic caused by `unwrap`
> Fix panics in `custom_at_rule` example

- src/properties/grid.rs
Make it possible to access the details of `repeat()` functions parsed from `grid_template_columns` / `grid_template_rows` properties.
We need this in order to use `lightningcss` for parsing CSS styles in https://github.com/DioxusLabs/blitz
Make the fields of the `TrackRepeat` struct public
> Make the fields of the `TrackRepeat` struct public

- website/pages/transforms.md
noticed that it would throw (using node:assert) when pasting the script
> AssertionError: '.foo{width:5.10424e38px}' == '.foo{width:24px}'
> docs: fix transforms example

- website/pages/docs.md
- website/pages/transpilation.md
https://sass-lang.com
https://github.com/sass/dart-sass
https://sass-lang.com/libsass
https://en.wikipedia.org/wiki/Sass_(stylesheet_language)
https://twitter.com/SassCSS
Sass is neither an acronym/initialism nor is it stylized as SASS anywhere. SCSS syntax meets this criteria, but Sass does not.
> Name casing: SASS → Sass

- node/index.d.ts
Adds missing `placeholder` property on the `ImportDependency` type
> fix: missing placeholder prop on ImportDependency type

- node/index.d.ts
> fix: BundleOptions should exclude analyzeDependencies

- .github/workflows/release-crates.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
The following updates are performed:
* update [`actions/checkout`](https://github.com/actions/checkout) to v3
* update [`actions/setup-node`](https://github.com/actions/setup-node) to v3
* replace [unmaintained](https://github.com/actions-rs/toolchain/issues/216) `actions-rs/toolchain` by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain)
* update [`bahmutov/npm-install`](https://github.com/bahmutov/npm-install) to v1.8.32
* update [`Swatinem/rust-cache`](https://github.com/Swatinem/rust-cache) to v2
Still using the unmaintained / outdated actions will generate several warnings in CI runs, for example in https://github.com/parcel-bundler/lightningcss/actions/runs/5299473633
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: …
> Update GitHub Actions CI

- node/index.d.ts
This makes it easier to use the interfaces from non-Node contexts like Deno (e.g. Deno.readFile returns an Uint8Array[1]).  The Buffer interface extends Uint8Array so this change should be compatible.
[1]: https://deno.land/api@v1.34.3?s=Deno.readFile
> Change Buffer to Uint8Array in node/index.d.ts

- src/media_query.rs
From https://github.com/szepeviktor/typos-on-you/actions/runs/5456995710
Could it be that this line is not covered by tests?
> Fix a typo in media_query

- .github/workflows/test.yml
- node/index.d.ts
- node/tsconfig.json
- package.json
Sorry I've been too quick on my previous update. I've added a CI check to avoid this kind of issues in the future
> Fix type usage of Features

- derive/src/lib.rs
- examples/custom_at_rule.rs
- node/src/transformer.rs
- src/properties/custom.rs
- src/rules/mod.rs
- src/selector.rs
- src/values/color.rs
- src/values/string.rs
- src/vendor_prefix.rs
- src/visitor.rs
It does not have to be `Sized`.
I'm trying to use `lightningcss` for some SWC-related projects and I need to create a trait object of `Visitor`
> feat: Make `Visitor` bounded by `?Sized`

- website/pages/docs.md
See https://github.com/parcel-bundler/lightningcss/issues/565
https://unpkg.com/lightningcss-wasm?module imports https://unpkg.com/napi-wasm@^1.0.1?module which responds with
```
Cannot generate module for napi-wasm@1.1.0/index.mjs
SyntaxError: unknown: Support for the experimental syntax 'classProperties' isn't currently enabled (32:10):
30 | 
31 | export class Environment {
> 32 |   scopes = [];
|          ^
33 |   referenceId = 1;
34 |   references = new Map();
35 |   deferred = [null];
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
undefined
```
https://esm.run (= [jsdelivr](https://www.jsdelivr.com/esm)) works fine
> Fix unpkg url in docs

- website/pages/docs.md
Vite since version 4.4.0 supports LightningCSS out of the box.
> docs: update vite usage docs

- wasm/index.mjs
If you always (conservatively) call `await init()`, e.g. like Parcel now does in CSSTransformer.js on every file transformer, the wasm module is constantly/re-initialized.
> Init Wasm module only once in browsers

- package.json
- scripts/build-wasm.js
- wasm/.gitignore
- wasm/import.meta.url-polyfill.js
- yarn.lock
* Brings WASM builds feature parity with exports from native builds
* Adds esbuild to convert to CJS (similar to other parcel repos)
> feat: support CJS output for wasm build

- src/lib.rs
- src/rules/property.rs
- src/values/syntax.rs
When declaring a `@property` with `syntax: '*'`, then the `initial-value` can be empty or can containe whitespace. Currently this errors with an `Unexpected end of input`.
This PR fixes that by allowing the whitespace in the `initial-value` spot.
I know it is 100% correct because we _do_ want to allow whitespace but just not print all of it.
- Right now I added it in a `syntax.rs` file and it's not _only_ for the `initial-value` but for everything that uses that parser with `SyntaxString::Universal` but I'm not 100% sure on how to fix this. A new property on the parser? An additional argument with some options?
- We also "abuse" the `EndOfInput` error in case of `initial-value:;`, this definitely feels hacky but I got it to work this way. Catching the `EndOfInput` allows us to convert it …
> Allow whitespace (or nothing) in the `initial-value` of `@property` with universal syntax

- Cargo.lock
- Cargo.toml
- node/test/bundle.test.mjs
- node/test/composeVisitors.test.mjs
- node/test/customAtRules.mjs
- node/test/transform.test.mjs
- node/test/visitor.test.mjs
- wasm/index.mjs
- wasm/wasm-node.mjs
The `ahash` crate has stopped compiling on `nightly` since today (https://github.com/tkaitchuck/aHash/issues/200). This broke many crates, including this one, and in turn also a part of the Rust compiler benchmark suite, which uses this crate as one of its runtime benchmarks :)
A newer version of `ahash` (`0.8.7`) is needed to fix the compilation issue. This PR updates the `ahash` dependency to fix the compilation of this crate on `nightly`:
```bash
$ cargo +nightly build --no-default-features --features grid,nodejs
```
However, it still won't work with default features, since `parcel_sourcemap` would also need to be updated.
> Update ahash to fix compilation issue on nightly

- napi/src/transformer.rs
This PR aims to make a stopgap workaround for https://github.com/napi-rs/napi-rs/issues/1641.
TL:DR, with latest napi `get_named_property`'s Result does not ensure if it's correct type of the value or not. It can be null|undefined, causes a failure later.
PR guards for the custom visitor logic to look up each properties - check its value type, then coerce into actual value. If upstream napi fixes this behavior it can go away, but anyone uses napi version ~today can benefit by this changes still.
> fix(visitor): check type for the underlying js object

- README.md
Stylo was recently [extracted from the servo repo](https://github.com/servo/servo/pull/31350) to it's own separate repo here: https://github.com/servo/stylo (_which includes the referenced `selectors` crate_).
I noticed this from the 404 on the README link, but perhaps this project references that link elsewhere too? (_I haven't checked_)
> docs: Update reference to Stylo

- Cargo.lock
- Cargo.toml
- napi/src/lib.rs
- src/css_modules.rs
- src/lib.rs
- src/printer.rs
- src/properties/animation.rs
- src/properties/grid.rs
- src/rules/keyframes.rs
- src/selector.rs
- src/values/ident.rs
- website/pages/css-modules.md
Adds granular options to switch on/off CSS module scoping for CSS features that are prefixed by default in Lightning CSS currently. For example animation, grid, and custom identifiers.
```js
let { code, map, exports } = transform({
// ...
cssModules: {
animation: true,
grid: true,
customIdents: true,
}
});
```
The reason this is useful is that for example Webpack's CSS modules implementation does not do prefixing of `grid`. If you're migrating to Lightning CSS, like we're doing in Next.js / Turbopack it's helpful to disable the grid prefixing feature to ensure people have a smooth experience migrating.
The PR is mostly done, just one more case with `animation: false` where it somehow uses `CustomIdent` which in turn means it still prefixes.
I'm not proficient in writing Rust currently, …
> Add granular CSS Modules options

- src/selector.rs
- tests/cli_integration_tests.rs
- See: https://github.com/vercel/next.js/issues/66191
- Closes https://github.com/parcel-bundler/lightningcss/issues/661
> fix: Fix codegen of `:is(input:checked)`

- Cargo.lock
- Cargo.toml
- c/Cargo.toml
- src/targets.rs
Bump browserslist-rs 0.16.0, be consistent with Parcel and SWC:
- https://github.com/parcel-bundler/parcel/pull/9838
- https://github.com/swc-project/swc/pull/9023
Changes
- https://github.com/browserslist/browserslist-rs/releases/tag/v0.16.0
> Bump browserslist-rs 0.16.0

- selectors/parser.rs
- src/error.rs
- src/selector.rs
- tests/cli_integration_tests.rs
Related: https://github.com/vercel/next.js/issues/64299
I made it a parse error because the specification about it is ambiguous thus it's better to bail out.
> feat: Add a lint for unsupported CSS Module selector

- src/lib.rs
- src/rules/keyframes.rs
Adds a new item to the `KeyframeSelector` enum for named timeline ranges (part of scroll-driven animations).
[Spec info](https://drafts.csswg.org/scroll-animations-1/#named-range-keyframes)
I ran `build-ast` but that changed a ton of things, so I didn't include that in this PR.
Fixes #786
> Add support for named timeline ranges in @keyframes

- scripts/build-wasm.js
This pull request adds the wasm file to the file exports. It allows esbuild to import the wasm file without copying it in the src directory, simplifying loading it in the browser when used in a library.
The tool I help maintain, updates CSS on the fly. Using lightningCSS in the browser was surprisingly easy.
The only true issue I had was init. When I run the init function:
```js
import initLightningCSS from 'lightningcss-wasm'
async function whereItsUsed(){
await initLightningCSS()
// ... the rest
}
```
I get an error about invalid URL when creating a URL object. Indeed, since I bundle using esbuild, `import.meta.url` is null. The `wasm` file cannot be resolved.
**Fortunately** the function accepts a parameter to tell it where the asset might be. This url is inside of `node_modules` which …
> feat: add wasm file to file exports

- selectors/parser.rs
- src/error.rs
- src/lib.rs
- src/properties/custom.rs
The previous error message was not human-readable.
```
Unexpected token Ident("h1")
```
> feat: Improve error message for pseudo elements followed by selectors

- napi/src/lib.rs
- selectors/parser.rs
- src/css_modules.rs
- src/error.rs
- src/lib.rs
- src/rules/mod.rs
- src/rules/scope.rs
- src/rules/style.rs
- src/selector.rs
- src/stylesheet.rs
- website/pages/css-modules.md
Relevant code: https://github.com/css-modules/postcss-modules-local-by-default/blob/5eeb3053bc40061022ebc6f41cd207a405484de1/src/index.js#L518-L520
> feat: Implement pure mode lints for CSS Modules

- src/lib.rs
- src/properties/box_shadow.rs
- closes https://github.com/parcel-bundler/lightningcss/issues/800
I'm not entirely sure but looking at the last PR https://github.com/parcel-bundler/lightningcss/pull/722, it seems `ColorFallbackKind::P3` case's `unwrap` was not handled.
> fix: fix `box-shadow` combination of `oklch` and `currentColor`

- website/index.html
The link at the bottom of the [Lightning CSS home page](https://lightningcss.dev/) is broken. I updated it to reflect the current location of selector logic
old link: https://github.com/servo/servo/tree/main/components/selectors
new link: https://github.com/servo/stylo/tree/main/selectors
> update broken selectors link in homepage

- website/pages/docs.md
Using single quotes in the CLI command will cause a panic in the main thread.
```
> lightningcss --bundle --targets '>= 0.5%' src/app.css -o dist/app.bundle.css
thread 'main' panicked at src/main.rs:191:56:
called `Result::unwrap()` on an `Err` value: Nom("")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This PR updates the example code to also work on Windows systems (wasn't immediately obvious that this was the problem).
> Make CLI example work with Windows (update docs.md)

- website/index.html
The copyright year is outdated. Simply update it with 2024.
> fix(website): Update copyright year on main page

- website/pages/transforms.md
This PR fixes the "TypeScript definitions" link on the [Custom transforms](https://lightningcss.dev/transforms.html#visitors) page.
- Fixed the line numbers.
- Changed to permalink so that the it doesn't break if the code gets moved.
> docs: fix link to visitor type definitions

- src/lib.rs
- src/values/color.rs
fix #685 
[playground repo](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20background%3A%20color-mix(in%20srgb%2C%20blue%2C%20accentcolor)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
> fix: should not panic when passing system-color to color-mix

- selectors/parser.rs
- src/error.rs
- src/lib.rs
- src/properties/animation.rs
- src/selector.rs
Another PR for improving the error message of selector parsing error.
I split `UnsupportedPseudoClassOrElement` into `UnsupportedPseudoClass` and `UnsupportedPseudoElement` so I can provide detailed error messages and suggestions for fix.
side note: I used ChatGPT to get an informative error message.
> feat: Improve error message of `input:placeholder`

- Cargo.lock
- c/build.rs
- selectors/Cargo.toml
- selectors/bloom.rs
- selectors/build.rs
- selectors/lib.rs
- selectors/matching.rs
- selectors/nth_index_cache.rs
- selectors/parser.rs
Plus crufty code from 2015 edition
> Dependency updates

- src/error.rs
- src/lib.rs
- src/parser.rs
It may cause confusion to the users because those are silently ignored.
https://github.com/vercel/next.js/issues/71479
> feat: Add an error for the deprecated `@value` at-rule of CSS Modules

- src/lib.rs
- src/printer.rs
- src/properties/transition.rs
This PR fixes an issue where using CSS that looks like this:
```css
.foo {
transition-property: -webkit-backdrop-filter, backdrop-filter;
}
```
Results in CSS that looks like this:
```css
.foo {
transition-property: -webkit-backdrop-filter, -webkit-backdrop-filter, backdrop-filter;
}
```
This PR solves it for the `transition-property` (internally `TransitionProperty`, so I think it's also solved for `transition` that uses that) only.
We currently do this by checking whether a `PropertyId` exists with `VendorPrefix::None`. If it does, then we will make sure to remove all other `PropertyId`'s (with the same name). The idea is that the `PropertyId` with `VendorPrefix::None` will print the property with the correct values, including the vendor prefix.
If however you only use CSS that looks …
> Fix duplicate `-webkit-backdrop-filter` output

- Cargo.lock
- Cargo.toml
- napi/src/transformer.rs
- node/ast.d.ts
- src/lib.rs
- src/parser.rs
- src/properties/font.rs
- src/rules/font_feature_values.rs
- src/rules/mod.rs
- src/visitor.rs
- static-self/Cargo.toml
- static-self/src/lib.rs
> feat: @font-feature-values

- node/index.d.ts
`Location` type does not have `source_index` property and `Location2` type have that.
`CustomAtRule.loc` was typed as `Location`, but the actual value had `source_index` property.
This PR changes the type of it to `Location2`.
> Fix CustomAtRule.loc type

- node/composeVisitors.js
- node/test/composeVisitors.test.mjs
`StyleSheet` / `StyleSheetExit` / `Rule.custom.*` was not called for visitors passed to `composeVisitors`. This PR fixes that.
Edit: just noticed that there was issue at #789, fixes #789, fixes #600
> Call StyleSheet / StyleSheetExit / Rule.custom.* in visitors passed to composeVisitors

- website/pages/transpilation.md
in https://lightningcss.dev/transpilation.html#color-function, the source example sets the `color` property but the compiled output has `background-color`. this makes them both set the `color` property.
> Docs: Fix color function compiled output

- cli/postinstall.js
- node/index.js
- package.json
This updates the detect-libc library to latest version for better compatibility. My specific issue was that this version is not compatible with the bun runtime.
> Update detect-libc for better compatibility

- src/values/number.rs
Fixes incorrect addition of an extra hyphen to CSS output for floating-point values that are sufficiently low to be represented by scientific notation.
If a value is represented by scientific notation, it may not be prefixed by "-0" but rather "-D", where D is some digit. In the code block below, if `number < 0` but `s` is not prefixed by "-0", then two hyphens are written. 
https://github.com/parcel-bundler/lightningcss/blob/0afd5d67196c1363e9f70aec8a763e786691255e/src/values/number.rs#L38C1-L49C13
This changes fixes this incorrect behavior by trimming additional leading hyphens ("-") from the string representation of the negative number.
This resolves issue with incorrect conversion from color-mix to oklab() (#899) resulting from double negative sign. 
This issue is urgent for myself, …
> Fix broken minification for non-opaque oklab colors 

- Cargo.lock
- Cargo.toml
- c/Cargo.toml
Bump browserslist-rs 0.17.0, be consistent with SWC:
- https://github.com/swc-project/swc/pull/9918
Changes:
- https://github.com/browserslist/browserslist-rs/releases/tag/v0.16.1
- https://github.com/browserslist/browserslist-rs/releases/tag/v0.17.0
> Bump browserslist-rs 0.17.0

- src/targets.rs
`browserslist::execute` is not available for wasm target, which breaks the compilation when enabling `browserslist` feature under wasm target.
> Add wasm compilation cfg for `Browsers::load_browserslist`

- src/lib.rs
- src/stylesheet.rs
This PR adds support for the `/* cssmodules-pure-no-check */` comment which allows users to disable the `pure` CSS modules check for the entire file (similar to `// @ts-nocheck`)
The feature is a port from [postcss](https://github.com/css-modules/postcss-modules-local-by-default?tab=readme-ov-file#pure-mode)
- **Parsing Change**: Detects the `/* cssmodules-pure-no-check */` comment at the beginning of the CSS file and sets `pure` to `false` in `css_modules` options.
- **Test Cases**: Added tests to verify the functionality, ensuring the comment works as expected even with preceding comments.
Solves #889
> allow to opt-out from css pure linting

- src/error.rs
The description for this error message is backwards.
> Fix error message for invalid composes selectors

- src/lib.rs
- src/media_query.rs
- src/parser.rs
- src/rules/container.rs
I'm trying to get some feedback before adding more test cases for error recovery.
Do you think this change sounds good to you?
- https://github.com/swc-project/plugins/pull/430
I'm trying to replace `swc_css` with `lightningcss` in `styled-jsx` (and turbopack), but I found an edge case where some more error recovery is necessary due to the way `styled-jsx` works.
> feat(parser): Improve error recovery of parser

- Cargo.lock
- Cargo.toml
browerslist-rs@0.18.1 supports `android 135` which aligns with browserslist which is needed in next-rspack https://github.com/vercel/next.js/discussions/77800#discussioncomment-12796398
> fix: upgrade browserslist

- src/lib.rs
- src/values/gradient.rs
- Fixes #918
- Ports angle conversion from [Autoprefixer’s implementation](https://github.com/postcss/autoprefixer/blob/541295c0e6dd348db2d3f52772b59cd403c59d29/lib/hacks/gradient.js#L103-L112). See this [comment](https://github.com/parcel-bundler/lightningcss/pull/936#discussion_r2039654448) for a more detailed comparison.
> Fix linear-gradient direction conversion for legacy vendor-prefixed values

- scripts/build-prefixes.js
- selectors/parser.rs
- src/compat.rs
- src/selector.rs
Closes https://github.com/parcel-bundler/lightningcss/issues/942
Adds support for
- https://developer.mozilla.org/en-US/docs/Web/CSS/::picker
- https://developer.mozilla.org/en-US/docs/Web/CSS/::picker-icon
- https://developer.mozilla.org/en-US/docs/Web/CSS/::checkmark
> Add support for `::picker`, `::picker-icon` and `::checkmark`

- Cargo.toml
- src/lib.rs
- src/properties/mod.rs
Fix #376
I removed the grid feature because it cannot be compiled with it disabled.
> Probably should just get rid of the grid feature actually. I had it there when it was still under development. None of the other individual properties have flags, so grid probably shouldn't either. Don't think it should cause much difference in compilation times.
https://github.com/parcel-bundler/lightningcss/issues/376#issuecomment-1367953788
> fix: remove grid feature

- src/lib.rs
- src/printer.rs
- src/stylesheet.rs
Right now putting license comments in a file causes invalid source maps to be generated.
For example, running this file through lightning with source maps will produce [incorrect generated locations](https://evanw.github.io/source-map-visualization/#NDQ4AC8qISBmb28gCiBmb28gCiBmb28gCiBmb28gKi8KLyohIGJhciAqLwouZmxleCB7CiAgZGlzcGxheTogZmxleDsKfQoKLmhpZGRlbiB7CiAgZGlzcGxheTogbm9uZTsKfQoKLyojIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2Jhc2U2NCxleUoyWlhKemFXOXVJam96TENKemIzVnlZMlZTYjI5MElqcHVkV3hzTENKdFlYQndhVzVuY3lJNkluZERRVXRCT3pzN08wRkJSMEVpTENKemIzVnlZMlZ6SWpwYkltbHVjSFYwTG1OemN5SmRMQ0p6YjNWeVkyVnpRMjl1ZEdWdWRDSTZXeUl2S2lFZ1ptOXZJRnh1SUdadmJ5QmNiaUJtYjI4Z1hHNGdabTl2SUNvdlhHNHZLaUVnWW1GeUlDb3ZYRzR1Wm14bGVDQjdYRzRnSUdScGMzQnNZWGs2SUdac1pYZzdYRzU5WEc0dWFHbGtaR1Z1SUh0Y2JpQWdaR2x6Y0d4aG …
> Prevent new lines written by `write_str` from breaking source maps

- src/targets.rs
For Turbopack we want to pass `ignore_unknown_versions` but that currently can't be passed to the browserslist parsing because it always defaults to the default options.
Initially thought about making `from_distribs` public but this can cause issues where browserslist versions mismatch when the application browserslist is a different version than the lightningcss browserslist.
Instead opted for re-exporting the browserslist config options from lightningcss and adding a new method for `from_browserslist_with_config`. The `_with_config` suffix because `from_browserslist` currently takes one argument and introducing a second argument would be a breaking change.
> Allow passing browserslist options to `from_browserslist`

- Cargo.lock
- Cargo.toml
- napi/Cargo.toml
- napi/src/transformer.rs
- src/properties/mod.rs
- src/rules/mod.rs
Fixes #1056
Uses the [serde-content](https://crates.io/crates/serde-content) crate to buffer during deserialization instead of internal private serde types, which have now moved.
> Use serde-content instead of private serde types
